# Generated by Django 3.1.6 on 2021-02-24 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0002_auto_20210224_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='number_ticket',
            name='user_profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mikrotik.user_profile'),
            preserve_default=False,
        ),
    ]
